env DOMAIN_NAME;
env BACKEND_PORT;

pid /tmp/nginx.pid;
worker_processes auto;


events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr;

    # Temp paths writable by non-root user
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    server {
        listen 80;
        server_name ${DOMAIN_NAME};

        location / {
            proxy_pass http://backend:${BACKEND_PORT};
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
